/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var e=Object.defineProperty;var r=Object.getOwnPropertyDescriptor;var p=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var u=(i,t)=>{for(var a in t)e(i,a,{get:t[a],enumerable:!0})},S=(i,t,a,o)=>{if(t&&typeof t=="object"||typeof t=="function")for(let s of p(t))!c.call(i,s)&&s!==a&&e(i,s,{get:()=>t[s],enumerable:!(o=r(t,s))||o.enumerable});return i};var d=i=>S(e({},"__esModule",{value:!0}),i);var m={};u(m,{default:()=>n});module.exports=d(m);var l=require("obsidian");var b=require("obsidian"),g={baseUrl:"https://gitlab.com"};var n=class extends l.Plugin{async onload(){await this.loadSettings()}onunload(){}async loadSettings(){this.settings=Object.assign({},g,await this.loadData())}async saveSettings(){await this.saveData(this.settings)}};
